"""AI coach study plans and chat messages."""

from __future__ import annotations

from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import Boolean, Enum, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base
from app.models.enums import CoachMessageRole, StudyPlanStatus
from app.models.mixins import TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.user import User


class StudyPlan(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Personalized multi-day prep plan generated by the AI coach."""

    __tablename__ = "study_plans"

    user_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[StudyPlanStatus] = mapped_column(
        Enum(StudyPlanStatus, name="study_plan_status", values_callable=lambda x: [e.value for e in x]),
        nullable=False,
        default=StudyPlanStatus.ACTIVE,
        server_default=StudyPlanStatus.ACTIVE.value,
        index=True,
    )
    weeks: Mapped[int] = mapped_column(Integer, nullable=False, default=2, server_default="2")
    focus_areas: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    model_provider: Mapped[str | None] = mapped_column(String(64), nullable=True)

    user: Mapped[User] = relationship(back_populates="study_plans")
    tasks: Mapped[list[StudyPlanTask]] = relationship(
        back_populates="plan",
        cascade="all, delete-orphan",
        order_by="StudyPlanTask.sequence",
    )


class StudyPlanTask(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """One actionable item inside a study plan."""

    __tablename__ = "study_plan_tasks"

    plan_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("study_plans.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    sequence: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    day_offset: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    category: Mapped[str] = mapped_column(String(64), nullable=False, default="general")
    estimated_minutes: Mapped[int] = mapped_column(Integer, nullable=False, default=30, server_default="30")
    resource_path: Mapped[str | None] = mapped_column(String(255), nullable=True)
    is_done: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False, server_default="false")

    plan: Mapped[StudyPlan] = relationship(back_populates="tasks")


class CoachMessage(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Short coach Q&A history (in-app mentoring)."""

    __tablename__ = "coach_messages"

    user_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    role: Mapped[CoachMessageRole] = mapped_column(
        Enum(CoachMessageRole, name="coach_message_role", values_callable=lambda x: [e.value for e in x]),
        nullable=False,
    )
    content: Mapped[str] = mapped_column(Text, nullable=False)
    extra: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    user: Mapped[User] = relationship(back_populates="coach_messages")
